# Generated by Django 3.0.4 on 2020-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about')),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects')),
                ('name', models.CharField(max_length=100, verbose_name='Project name')),
                ('description', models.TextField(verbose_name='About project')),
                ('github_url', models.TextField(verbose_name='Github url')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='skills')),
                ('name', models.CharField(max_length=100, verbose_name='skill name')),
                ('technologies', models.TextField(verbose_name='Technologies')),
            ],
        ),
    ]
